# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  terraform-setup:
    docker:
      - image: mullnerz/ansible-playbook:latest
    steps:
      - checkout
      - run: |
          echo $BASE64_PEM_FILE | base64 -d > id_rsa
          echo $BASE64_PUB_KEY | base64 -d > id_rsa.pub
          chmod 400 id_rsa
      - run: |
          curl -o tf0.12.zip https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip
          unzip tf0.12.zip
          mv terraform /usr/bin/
      - run: terraform init
      - run: terraform apply -input=false -auto-approve
      - run: sleep 10s
      - run: terraform destroy -auto-approve
      - store_artifacts:
          path: ./terraform.tfstate
          when: always

workflows:
  deploy:
    # Run the welcome/run job in its own container
    jobs:
      - terraform-setup:
          filters:
            ignore:
              - /.*skip-build/